### ISSUE TITLE
Flow rate

### ISSUE THREAD

**Issue by tomcorker** [glynhudson/samsung-modbus-mim-b19n#1]
Thanks for this Glyn, helped me integrate my Samsung heat pump with Home Assistant.

I worked out the issue with flow rate not updating - you need to use write_registers() to add all the indoor functions you want in one go using Modbus command 16:

```
# Flow rate in L/min
# FR control
# 3 way valve position. 0=CH, 1=DHW
instrument.write_registers(7005,[0x42E9, 0x42F1, 0x4067])
```

**Comment by glynhudson** [comment]
Fantastic! The flow rate being laggy has been a significant issue that would be great to fix. I'll give this a try. 

Have you been able to read or control the compressor frequency? I never had any luck doing either of these. 

Also, have you got any idea why the outdootT metric returns the value `6550.11`  when the outdoorT is negative?

**Comment by glynhudson** [comment]
Confirmed, flow rate issue has been fixed. Thanks a lot 👍
